# Site settings
title: Unlikely Developer
header-img: img/home-bg.png
email: nickalan82@icloud.com
copyright_name: Nick-Damico
description: > # this means to ignore newlines until "baseurl:"
  Techdegree Graduate | FlatIronSchool Student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: NickAlan82
github_username:  Nick-Damico
learn_profile: Nick-Damico
email_username: nickalan82@icloud.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
